site_name: Maheshrjl's Notes
theme:
  name: material
  palette: 
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: white
      toggle:
        name: Dark mode
        icon: material/weather-sunny

    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: black
      toggle:
        name: Light mode
        icon: material/weather-night

  font: 
    text: Roboto
    code: Fira Code

  logo: assets/logo.png
  favicon: assets/favicon.png

  features:
    - navigation.instant
    - navigation.tabs

nav:
  - index.md
  - about.md

plugins:
  - search
  - privacy